// Code generated by github.com/ARUMANDESU/gobuildergen. DO NOT EDIT.
package domain


type LibraryItemBuilder struct {
    val LibraryItem
}

func NewLibraryItemBuilder() *LibraryItemBuilder {
    return &LibraryItemBuilder{}
}

func (b *LibraryItemBuilder) WithDefault() *LibraryItemBuilder {
    return b
}

func (b *LibraryItemBuilder) Id(v LibraryItemID) *LibraryItemBuilder {
    b.val.id = v
    return b
}

func (b *LibraryItemBuilder) Title(v string) *LibraryItemBuilder {
    b.val.title = v
    return b
}

func (b *LibraryItemBuilder) ItemType(v LibraryItemType) *LibraryItemBuilder {
    b.val.itemType = v
    return b
}

func (b *LibraryItemBuilder) AuthorIDs(v []AuthorID) *LibraryItemBuilder {
    b.val.authorIDs = v
    return b
}

func (b *LibraryItemBuilder) Genre(v []string) *LibraryItemBuilder {
    b.val.genre = v
    return b
}

func (b *LibraryItemBuilder) Languages(v []string) *LibraryItemBuilder {
    b.val.languages = v
    return b
}

func (b *LibraryItemBuilder) Annotation(v string) *LibraryItemBuilder {
    b.val.annotation = v
    return b
}

func (b *LibraryItemBuilder) Build() LibraryItem {
    return b.val
}
