// Code generated by github.com/ARUMANDESU/gobuildergen. DO NOT EDIT.
package domain


type UserBuilder struct {
    val User
}

func NewUserBuilder() *UserBuilder {
    return &UserBuilder{}
}

func (b *UserBuilder) WithDefault() *UserBuilder {
    b.val.id = NewUserID()
    b.val.name = ValidUsername
    return b
}

func (b *UserBuilder) Id(v UserID) *UserBuilder {
    b.val.id = v
    return b
}

func (b *UserBuilder) Name(v string) *UserBuilder {
    b.val.name = v
    return b
}

func (b *UserBuilder) PassHash(v []byte) *UserBuilder {
    b.val.passHash = v
    return b
}

func (b *UserBuilder) Build() User {
    return b.val
}
